In [ ]:
#create model class has 1 neuron
import torch
import torch.nn as nn

In [ ]:
class Model(nn.Module):
  def __init__(self,num_features):#pass the total feature
    super().__init__()
    #input = num_features
    self.linear = nn.Linear(num_features,1)#input,output
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features) #we are calculating wx+b
    out = self.sigmoid(out)
    return out


In [ ]:
#dataset
features = torch.rand(10,5)

#create model
model = Model(features.shape[1])

#call forward pass
model(features)#standard way of calling insted of model.fordward()

#

tensor([[0.4869],
        [0.5071],
        [0.5817],
        [0.5155],
        [0.5358],
        [0.4801],
        [0.5162],
        [0.5167],
        [0.5293],
        [0.5004]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear.weight

Parameter containing:
tensor([[-0.0524, -0.0579, -0.3813, -0.0954,  0.2484]], requires_grad=True)

In [ ]:
model.linear.bias

Parameter containing:
tensor([0.2750], requires_grad=True)

In [ ]:
!pip install torchinfo

In [ ]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
class Model(nn.Module):
  def __init__(self,num_features):#pass the total feature
    super().__init__()
    #input = num_features
    self.linear1 =

  def forward(self,features):
    out = self.linear(features) #we are calculating wx+b
    out = self.sigmoid(out)
    return out